export const CATEGORIES_ACTIONS = {
    FETCH_CATEGORIES_START: 'categories/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'categories/FETCH_CATEGORIES_START_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'categories/FETCH_CATEGORIES_START_FAILED'
}