
export const CART_ACTIONS_TYPES = {
    SET_TOGGLE_CART: "cart/SET_TOGGLE_CART",
    SET_CART_ITEMS: "cart/SET_CART_ITEMS",
    SET_CART_COUNT: "cart/SET_CART_COUNT",
    SET_CART_TOTAL: "cart/SET_CART_TOTAL",
};